prgrms-web-devcourse-final-project/WEB4_5_DOD_FE

src/app/schedule/[Id]/election/start-point/page.tsx, src/components/feature/kakaoMap/SubwaySearch.tsx, src/components/ui/BottomSheet.tsx, src/components/ui/SubwaySearchResultList.tsx
- 바텀 시트 오류 해결
- 바텀 시트 차등 높이 적용 (웹/모바일)
---
---
---
=> [Style] 바텀 시트 높이 차등 적용

src/components/layout/Header.tsx, src/lib/profileImages.ts
---
- 웹헤더 유저 유무에 따른 아이콘 및 버튼 렌더링 
---
---
---
이렇게 하는게 맞나여.. ㅎ
=> [Feat] 웹헤더 -  유저 유무에 따른 헤더 변경 (로그인버튼, 유저프로필 렌더링)

src/components/layout/Header.tsx
---
- 헤더 프로필과 로그인 버튼 동시에 나오는 오류 수정했습니다. 
---
---
---
- 다른 오류 하나 더 해결하고 또 커밋 올리겠습니당..
=> [Fix]  헤더 - 프로필 렌더링 오류 수정

src/app/meeting/[eventId]/coordinate/[groupId]/page.tsx, src/components/feature/CommonSchedule.tsx, src/components/feature/Schedule.tsx, src/components/feature/meeting/coordinate/ActionMyButton.tsx, src/components/feature/meeting/coordinate/LoadButton.tsx, src/components/feature/meeting/coordinate/ScheduleSection.tsx, src/components/mypage/TimeSheet.tsx, src/components/ui/AlertBox.tsx, src/lib/api/scheduleApi.ts, src/types/schedule.d.ts
---
이벤트에서 내 시간표 불러오기 기능 구현
"내 시간표 등록" 버튼 클릭시 UI/UX 개선
---
---
---
마이페이지에서 시간표 수정 시에 이용 가능함
=> [Feat] 내 시간표 불러오기 기능 구현

src/components/feature/group/members/MemberList.tsx
---
그룹 멤버 리스트 모션 애니메이션 적용
---
---
https://github.com/user-attachments/assets/2f906c91-fe86-4805-9942-e0742ea66a05
---
=> [Feat] 그룹 멤버 리스트 모션 애니메이션 적용

src/app/schedule/[Id]/election/start-point/page.tsx, src/app/schedule/[Id]/election/start/page.tsx
헤더 재연결 후 api 연결했습니다.
---
---
---
=> [Style] 헤더 연결

src/components/feature/Schedule.tsx, src/components/mypage/TimeSheet.tsx
---
마이페이지 즐겨찾는 시간대 저장 오류 수정
---
---
---
=> [Fix] 마이페이지 시간표 저장 로직 오류 수정

src/app/meeting/[eventId]/coordinate/[groupId]/page.tsx, src/app/meeting/[eventId]/coordinate/page.tsx, src/app/schedule/[id]/edit/detail/page.tsx, src/app/schedule/[id]/edit/workspace/layout.tsx, src/app/schedule/[id]/edit/workspace/page.tsx, src/app/schedule/[id]/election/page.tsx, src/app/schedule/[id]/election/result/page.tsx, src/app/schedule/[id]/election/start-point/page.tsx, src/app/schedule/[id]/election/start/page.tsx, src/app/schedule/[id]/election/wait/page.tsx, src/app/schedule/[id]/page.tsx, src/app/schedule/complete/[eventId]/page.tsx, src/app/schedule/create/page.tsx, src/components/feature/CommonSchedule.tsx, src/components/feature/Schedule.tsx, src/components/feature/meeting/TimeResult.tsx, src/components/feature/meeting/TimeResultScheduleCard.tsx, src/components/feature/meeting/coordinate/ActionButtons.tsx, src/components/feature/meeting/coordinate/CoordinateContent.tsx, src/components/feature/meeting/coordinate/ScheduleSection.tsx, src/components/feature/meeting/coordinate/TitleWithShare.tsx, src/components/feature/schedule/ScheduleSelectDate.tsx, src/lib/api/groupApi.ts, src/types/kakao.d.ts
---
이벤트 생성 시 캘린더에서 과거 날짜 선택시 Toast 알림과 함께 선택 안되게 개선
그룹 일정 생성에서 이벤트 초대시 해당 그룹에 자동으로 가입되도록 개선
함께 가능한 시간대 의 폰트 크기 수정
시간표의 날짜 부분 폰트 크기 수정
월요일 시간표 등록시 안보이는 오류 수정
조율결과에서 일정 확정시 API 오류 수정
Id -> id 로 수정
---
---
---
=> [Fix] 버그 수정

src/app/schedule/[id]/edit/detail/page.tsx, src/app/schedule/[id]/edit/workspace/page.tsx, src/app/schedule/[id]/page.tsx, src/components/feature/meeting/coordinate/CoordinateContent.tsx, src/components/feature/schedule/ScheduleSelectDate.tsx, src/lib/api/scheduleApi.ts
Reverts prgrms-web-devcourse-final-project/WEB4_5_DOD_FE#132
=> Revert "[Fix] 오류 수정"

src/lib/api/authApi.ts
---
- 프로필 업데이트 query invalidation 수정해서 프로필 변경 후 대시보드에 있는 모임 프로필 이미지 즉시 변경 된 걸 볼 수 있게 했습니당 
---
---
---
=> [Fix]   프로필 업데이트  query invalidation 수정

src/app/layout.tsx
=> [Fix] og 설정 수정

src/app/schedule/[id]/election/start-point/page.tsx, src/components/feature/kakaoMap/SubwaySearch.tsx, src/lib/api/ElectionApi.ts, src/types/schedule.d.ts
- 사용자가 이미 출발 장소를 등록하고 다시 카톡 공유하기로 들어올 경우 대기 페이지로 리다이렉트
---
---
=> [Feat] 장소 등록 재진입 예외처리

src/app/schedule/[id]/election/page.tsx, src/app/schedule/[id]/election/start-point/page.tsx, src/app/schedule/[id]/election/wait/page.tsx, src/app/utils/getTotalTravelTime.ts, src/components/feature/kakaoMap/SubwaySearch.tsx, src/lib/api/ElectionApi.ts
- 등록한 장소로 지도가 안찍히는 버그 수정
- 즐겨찾기 장소 불러오는 버튼 추가
- 바텀 시트 10% 씩 높이 올림
---
---
---
=> [Feat] 즐겨 찾기 장소 불러오기

src/app/mypage/page.tsx, src/lib/api/authApi.ts
---
- 비로그인 접근제한 추가 (로그인 페이지로 리다이렉트)
- 장소 등록 api 변수 추가 ( address)
---
---
---
- 역 등록 오류나서 수정중입니다.....
=> [Fix] 마이페이지 -  비로그인 페이지 접근제한 추가 및 장소 api 변수 address 추가

src/components/dashboard/LoadUserSchedule.tsx, src/components/feature/group/EditGroupPage.tsx, src/components/feature/group/GroupSchdeduleCreateSelectPage.tsx, src/components/feature/group/analytics/hooks/useGroupAnalyticsData.ts, src/components/feature/group/members/hooks/useGroupMemberLogic.ts, src/components/feature/schedule/detail/ScheduleDetail.tsx, src/components/feature/schedule/edit/workspace/EditWorkspace.tsx, src/components/feature/schedule/editSchedule/EditScheduleInfoPage.tsx, src/components/feature/schedule/hooks/useAuthRequired.ts, src/lib/api/groupApi.ts
---
새로고침시 user 값 못불러와 로그인 페이지로 리다이렉트 되는 오류 해결 
- 그룹 페이지
- 그룹 통계 페이지
- 그룹 멤버 페이지
- 그룹 일정 생성 선택 페이지
- 그룹 일정 불러오기 페이지
- 그룹 수정 페이지
- 일정 페이지
- 일정 수정 페이지
- 일정 워크스페이스 관리 페이지
useAuthRequired.ts 수정
```
const [isMounted, setIsMounted] = useState(false);
useEffect(() => {
setIsMounted(true);
}, []);
useEffect(() => {
const checkAuth = () => {
if (user) {
setIsAuthenticated(true);
setIsLoading(false);
} else if (!user && isMounted) {
setIsAuthenticated(false);
Toast("로그인 후 이용해주세요.");
router.replace("/auth/login");
}
};
checkAuth();
}, [user, router, isMounted]);
```
isMounted 상태 관리로 새로고침 시 use null 값일때 로그인 페이지 리다이렉트 방지
---
---
---
=> Fix: 새로고침시 user 데이터 잠시 못가져올때 로그인 리다이렉트 이동시키는 오류 해결

src/components/feature/Schedule.tsx
---
기존에 등록 한 시간과 비교하여 등록하는데 이미 등록된 시간을 빼버리는 버그가 있어서 수정
---
---
---
=> [Fix] 시간표 등록시 기존 시간 사라지는 버그 수정

src/components/feature/meeting/TimeResult.tsx
---
드롭 다운으로 값 변경시 표기값 변경 안되는 버그 수정
---
---
---
=> [Fix] 리스트 값 변경 오류 수정

src/components/landing/Section2.tsx, src/components/landing/TextMessage.tsx
---
Landing 페이지 Section2
휴대폰 채팅 애니메이션 iphone12 pro 이하 사이즈의 기종 대응 반응형 적용
---
---
---
=> [Style] 랜딩페이지 Section2 iphone 12pro 및 사이즈 작은 휴대폰 대응 반응형 적용

src/components/feature/schedule/editSchedule/hooks/useOnlineMeetingForm.ts
기존 온라인 회의장 삭제 request body
```
{
meetingPlatform: "NONE",
platformURL: null,
},
```
변경된 온라인 회의장 삭제 request body
{
meetingPlatform: "NONE",
platformURL:"",
},
---
Landing 페이지 Section2
휴대폰 채팅 애니메이션 iphone12 pro 이하 사이즈의 기종 대응 반응형 적용
---
---
---
=> [Fix] Api 변경으로 인한 온라인 회의장 삭제 request body 변경

src/components/feature/meeting/coordinate/ActionMyButton.tsx
---
무한 츠쿠요미 걸려서 push 에서 back 으로 수정
my -> coordinate -> my -> ...
---
---
---
=> Fix: 뒤로가기 무한 반복 수정

src/components/feature/schedule/ScheduleSelectDate.tsx, src/components/ui/ScheduleButton.tsx
---
시작 시간과 종료 시간이 같은경우 예외
시작 시간이 종료 시간보다 빠를 경우 예외
00 ~ 24 시 까진데 00 과 24 로 선택할 경우 오류 나므로 24는 제외
---
---
---
=> [Fix] 이벤트 생성의 시간 선택 예외 처리

src/lib/api/groupApi.ts
---
변경 내용
useGroupSchedules: staleTime 5분 → 1분
useGroupMembers: staleTime 5분 → 3분
useGroupStatistics: gcTime 10분 → 15분
변경 이유
- 일정 데이터: 자주 수정되므로 빠른 동기화 필요하다고  판단
- 통계 데이터: 실시간성 덜 중요하므로 캐시 시간 연장
- 멤버 데이터: 중간 빈도로 변경
---
---
---
=> [Refactor] tanstack query 캐시 시간 변경 
